// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyCrypto.Data;

namespace MyCrypto.Data.Migrations
{
    [DbContext(typeof(MyCryptoContext))]
    partial class MyCryptoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("MyCrypto.Core.Models.AddedCoin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CoinNameId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AddedCoins");
                });
#pragma warning restore 612, 618
        }
    }
}
